### PR TITLE
Import Extension from setuptools instead of Cython

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by lpsinger** [comment]
There was a good reason why it was imported from cython, but I don't remember what that reason was. Why change it?

**Comment by zonca** [comment]
see #686

**Comment by lpsinger** [comment]
I tried to reproduce this in a fresh docker container, but I can't. Would you please provide step-by-step instructions to reproduce?

```
gs66-wintermute:~ lpsinger$ docker run --rm -it python:3.8 bash
root@ceaefb3788ba:/# pip install setuptools cython numpy
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (56.0.0)
Collecting cython
  Downloading Cython-0.29.23-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 947 kB/s 
Collecting numpy
  Downloading numpy-1.20.2-cp38-cp38-manylinux2010_x86_64.whl (15.4 MB)
     |████████████████████████████████| 15.4 MB 1.2 MB/s 
Installing collected packages: numpy, cython
Successfully installed cython-0.29.23 numpy-1.20.2
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
root@ceaefb3788ba:/#  git clone --recurse-submodules https://github.com/healpy/healpy
Cloning into 'healpy'...
remote: Enumerating objects: 7009, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 7009 (delta 26), reused 35 (delta 15), pack-reused 6948
Receiving objects: 100% (7009/7009), 16.43 MiB | 727.00 KiB/s, done.
Resolving deltas: 100% (4014/4014), done.
Submodule 'cfitsio' (https://github.com/healpy/cfitsio.git) registered for path 'cfitsio'
Submodule 'healpixsubmodule' (https://github.com/healpy/healpixmirror.git) registered for path 'healpixsubmodule'
Cloning into '/healpy/cfitsio'...
remote: Enumerating objects: 486, done.        
remote: Counting objects: 100% (52/52), done.        
remote: Compressing objects: 100% (46/46), done.        
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/healpy/cfitsio.git' into submodule path '/healpy/cfitsio' failed
Failed to clone 'cfitsio'. Retry scheduled
Cloning into '/healpy/healpixsubmodule'...
remote: Enumerating objects: 13114, done.        
remote: Counting objects: 100% (739/739), done.        
remote: Compressing objects: 100% (338/338), done.        
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/healpy/healpixmirror.git' into submodule path '/healpy/healpixsubmodule' failed
Failed to clone 'healpixsubmodule'. Retry scheduled
Cloning into '/healpy/cfitsio'...
remote: Enumerating objects: 486, done.        
remote: Counting objects: 100% (52/52), done.        
remote: Compressing objects: 100% (46/46), done.        
remote: Total 486 (delta 10), reused 20 (delta 6), pack-reused 434        
Receiving objects: 100% (486/486), 17.63 MiB | 777.00 KiB/s, done.
Resolving deltas: 100% (243/243), done.
Cloning into '/healpy/healpixsubmodule'...
remote: Enumerating objects: 13114, done.        
remote: Counting objects: 100% (739/739), done.        
remote: Compressing objects: 100% (338/338), done.        
remote: Total 13114 (delta 439), reused 514 (delta 395), pack-reused 12375        
Receiving objects: 100% (13114/13114), 130.36 MiB | 900.00 KiB/s, done.
Resolving deltas: 100% (9727/9727), done.
Submodule path 'cfitsio': checked out '33e552441d38d49d5305fb9f9ea38eadf72dcf80'
Submodule path 'healpixsubmodule': checked out 'c82a2bdb99b04a87207513418225b18196e91b57'
Submodule path 'cfitsio': checked out '33e552441d38d49d5305fb9f9ea38eadf72dcf80'
Submodule path 'healpixsubmodule': checked out 'c82a2bdb99b04a87207513418225b18196e91b57'
root@ceaefb3788ba:/# cd healpy
root@ceaefb3788ba:/healpy# pip install .
Processing /healpy
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting matplotlib
  Downloading matplotlib-3.4.1-cp38-cp38-manylinux1_x86_64.whl (10.3 MB)
     |████████████████████████████████| 10.3 MB 9.3 MB/s 
Collecting astropy
  Downloading astropy-4.2.1-cp38-cp38-manylinux1_x86_64.whl (9.8 MB)
     |████████████████████████████████| 9.8 MB 8.0 MB/s 
Collecting scipy
  Downloading scipy-1.6.3-cp38-cp38-manylinux1_x86_64.whl (27.2 MB)
     |████████████████████████████████| 27.2 MB 9.5 kB/s 
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.8/site-packages (from healpy==1.14.0) (1.20.2)
Collecting pyerfa
  Downloading pyerfa-1.7.3-cp38-cp38-manylinux2010_x86_64.whl (731 kB)
     |████████████████████████████████| 731 kB 7.1 MB/s 
Collecting pyparsing>=2.2.1
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 4.4 MB/s 
Collecting python-dateutil>=2.7
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 9.5 MB/s 
Collecting pillow>=6.2.0
  Downloading Pillow-8.2.0-cp38-cp38-manylinux1_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 5.7 MB/s 
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.1-cp38-cp38-manylinux1_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 6.5 MB/s 
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: healpy
  Building wheel for healpy (PEP 517) ... done
  Created wheel for healpy: filename=healpy-1.14.0-cp38-cp38-linux_x86_64.whl size=19929520 sha256=663e733e107ff00d78b580eb7cc1f6cf7f8191b2aac421e12716835d8e5cc815
  Stored in directory: /tmp/pip-ephem-wheel-cache-rtowsk50/wheels/e3/9e/a7/46d60f48259d4bba0828580a2c86cabac8338f3ca3892479ac
Successfully built healpy
Installing collected packages: six, python-dateutil, pyparsing, pyerfa, pillow, kiwisolver, cycler, scipy, matplotlib, astropy, healpy
Successfully installed astropy-4.2.1 cycler-0.10.0 healpy-1.14.0 kiwisolver-1.3.1 matplotlib-3.4.1 pillow-8.2.0 pyerfa-1.7.3 pyparsing-2.4.7 python-dateutil-2.8.1 scipy-1.6.3 six-1.16.0
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
root@ceaefb3788ba:/healpy# 
```

**Comment by zonca** [comment]
```
> conda create -n testcython python==3.8 numpy cython astropy

> conda list

_libgcc_mutex             0.1                        main  
astropy                   4.2.1            py38h6323ea4_1  
blas                      1.0                         mkl  
ca-certificates           2021.4.13            h06a4308_1  
certifi                   2020.12.5        py38h06a4308_0  
cython                    0.29.23          py38h2531618_0  
intel-openmp              2021.2.0           h06a4308_610  
libedit                   3.1.20210216         h27cfd23_1  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
mkl                       2021.2.0           h06a4308_296  
mkl-service               2.3.0            py38h27cfd23_1  
mkl_fft                   1.3.0            py38h42c9631_2  
mkl_random                1.2.1            py38ha9443f7_2  
ncurses                   6.2                  he6710b0_1  
numpy                     1.20.1           py38h93e21f0_0  
numpy-base                1.20.1           py38h7d8b39e_0  
openssl                   1.1.1k               h27cfd23_0  
pip                       21.0.1           py38h06a4308_0  
pyerfa                    1.7.3            py38h27cfd23_0  
python                    3.8.0                h0371630_2  
readline                  7.0                  h7b6447c_5  
setuptools                52.0.0           py38h06a4308_0  
six                       1.15.0           py38h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
```

on current main 46b23770a3b09d319edf6a0c6b1b1bf6cf86a748:
```
python setup.py build
running build
running build_py
copying healpy/__init__.py -> build/lib.linux-x86_64-3.8/healpy
copying healpy/pixelfunc.py -> build/lib.linux-x86_64-3.8/healpy
copying healpy/sphtfunc.py -> build/lib.linux-x86_64-3.8/healpy
copying healpy/visufunc.py -> build/lib.linux-x86_64-3.8/healpy
copying healpy/fitsfunc.py -> build/lib.linux-x86_64-3.8/healpy
copying healpy/projector.py -> build/lib.linux-x86_64-3.8/healpy
copying healpy/rotator.py -> build/lib.linux-x86_64-3.8/healpy
copying healpy/projaxes.py -> build/lib.linux-x86_64-3.8/healpy
copying healpy/cookbook.py -> build/lib.linux-x86_64-3.8/healpy
copying healpy/newvisufunc.py -> build/lib.linux-x86_64-3.8/healpy
copying healpy/zoomtool.py -> build/lib.linux-x86_64-3.8/healpy
copying healpy/configure_logging.py -> build/lib.linux-x86_64-3.8/healpy
copying healpy/test/test_fitsfunc.py -> build/lib.linux-x86_64-3.8/healpy/test
running build_clib
checking if configure script for library 'cfitsio' exists
checking if configure script for library 'sharp' exists
checking if configure script for library 'healpix_cxx' exists
checking if library 'cfitsio' is installed
found 'cfitsio' installed, using it
checking if library 'sharp' is installed
found 'sharp' installed, using it
checking if library 'healpix_cxx' is installed
found 'healpix_cxx' installed, using it
running build_ext
error: each element of 'ext_modules' option must be an Extension instance or 2-tuple
```

It works fine on 1.14.0....so I think it must be the line integral convolution extension.

**Comment by lpsinger** [comment]
I see. I can reproduce it.

**Pull request merged**
