### PR TITLE
update cfitsio to 3.47

### PR DESCRIPTION
**Pull request by zonca**
https://github.com/healpy/healpy/issues/592

### CODE REVIEW

**Comment by zonca** [comment]
@mreineck @lpsinger  I have trouble updating CFITSIO,
it seems like I can build libcfitsio, but the HEALPix configure script cannot find it.
See https://travis-ci.com/github/zonca/healpy/jobs/344641606#L1843

Would you have any suggestion on what is wrong?

**Comment by mreineck** [comment]
`configure` complains because it can find the cfitsio library file, but it doesn't contain the `fngrwll` symbol. Most likely this happens because cfitsio was compiled without large file support, see, e.g., https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/f_user/node13.html
But I do not understand why this should have suddenly been turned off ...

**Comment by mreineck** [comment]
I just checked the Travis build log ... large file support seems to be enabled. Weird.

**Comment by mreineck** [comment]
Is there any way to access the `config.log` and other files generated by `configure` during the Travis build?

**Comment by zonca** [comment]
@mreineck sure, I can reproduce it on my Ubuntu, it was just easier to upload everything to a throwaway repo:

https://github.com/zonca/build_logs_cfitsio

**Comment by mreineck** [comment]
Thanks!
Here is what I think is happening: `configure` does actually find libcfitsio.so, but when it tries to link against it in order to look for the `ffgnrwll` symbol, `libcfitsio` itself requires `libcurl` and that is not found (for a reason I don't understand).
To be honest, I don't understand how `libcfitsio` is built during the configuration of `Healpix_cxx` if it is not found on the system. It seems as if `pkgconfig` is trying to do this and failing.
In any case I don't think that Healpix has been requiring a pre-installed `libcfitsio` for some time now; if the installation via `pkgconfig` worked up to now, that was a lucky accident.

**Comment by zonca** [comment]
I think `libcurl` is there, but during configure:

```
configure:17569: x86_64-linux-gnu-gcc -pthread -o conftest -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -      
fstack-protector-strong -Wformat -Werror=format-security -fopenmp -I/home/zonca/zonca/p/software/healpy/build/temp.linux-x86_64-3.7/ 
include  -fopenmp  conftest.c -lcfitsio   -L/home/zonca/zonca/p/software/healpy/build/temp.linux-x86_64-3.7/lib -lcfitsio -lm >&5
```

this should also have `-lcurl`

**Comment by mreineck** [comment]
I agree, but this should be set automatically by the `pkg-config` description file coming with `cfitsio`. I don't know how this can be done from the "customer" side, because some versions of `libcfitsio` depend on curl and some don't.

**Comment by mreineck** [comment]
I'm glad that this won't be an issue any more at some point in the future ;-)

**Comment by mreineck** [comment]
I suspect that the `cfitsio` in question is installed without a `pkgconfig` file, and therefore `configure` falls back to the bare `-lcfitsio` flag (see lines 49-53 in `src/cxx/configure.ac`)

**Comment by zonca** [comment]
`lib/pkgconfig/cfitsio.pc`

is

```
prefix=/home/zonca/zonca/p/software/healpy/build/temp.linux-x86_64-3.7
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: cfitsio
Description: FITS File Subroutine Library
URL: https://heasarc.gsfc.nasa.gov/fitsio/
Version: 3.48
Libs: -L${libdir} -lcfitsio
Libs.private: -lm 
Cflags: -I${includedir}
```

**Comment by mreineck** [comment]
If `libcfitsio` needs the `-lcurl` flag when being linked to a binary, then it should be in there ...
I'm not absolutely sure that it is actually needed (since shared libraries can track their own dependencies to some extent), but if not, why does the `configure` test fail?
Can you try to add `-lcurl` temporarily to the "Libs:" line?

**Comment by zonca** [comment]
we are using the static libraries, this worked on my machine!
thanks for your help debugging. let's hope for Travis to work as well.

**Comment by mreineck** [comment]
OK, let's hope for the best!

**Comment by zonca** [comment]
That was it, thanks!

**Pull request merged**
