### PR TITLE
update cfitsio to 4.0.0

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by zonca** [comment]
Linked to #741

**Comment by zonca** [comment]
@mreineck I see these errors in the log of Github Actions:

```
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.6447470Z   ERROR: Command errored out with exit status 1:
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.6702479Z    3845 |     snprintf(errorstr,SHORTLEN,"ERROR ftp_status wants %s but got unexpected %s", statusstr, recbuf);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.6703688Z    3845 |     snprintf(errorstr,SHORTLEN,"ERROR ftp_status wants %s but got unexpected %s", statusstr, recbuf);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.6704976Z    3838 |       snprintf(errorstr,SHORTLEN,"ERROR ftp_status wants %s but got %s", statusstr, recbuf);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.6888698Z    3838 |       snprintf(errorstr,SHORTLEN,"ERROR ftp_status wants %s but got %s", statusstr, recbuf);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7202112Z    3118 |                 "Error reading EXTEND keyword value as a logical: %s", value);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7203646Z    3118 |                 "Error reading EXTEND keyword value as a logical: %s", value);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7204903Z    3101 |                 "Error reading GCOUNT keyword value as an integer: %s", value);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7206432Z    3101 |                 "Error reading GCOUNT keyword value as an integer: %s", value);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7207631Z    3088 |                 "Error reading PCOUNT keyword value as an integer: %s", value);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7209162Z    3088 |                 "Error reading PCOUNT keyword value as an integer: %s", value);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7210415Z    3075 |                 "Error reading BLANK keyword value as an integer: %s", value);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7211977Z    3075 |                 "Error reading BLANK keyword value as an integer: %s", value);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7213322Z    3058 |                 "Error reading BZERO keyword value as a double: %s", value);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7215292Z    3058 |                 "Error reading BZERO keyword value as a double: %s", value);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7216703Z    3041 |                 "Error reading BSCALE keyword value as a double: %s", value);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7218683Z    3041 |                 "Error reading BSCALE keyword value as a double: %s", value);
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7692636Z   configure: error: could not find the cfitsio library
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7696956Z   subprocess.CalledProcessError: Command '('pkg-config', '--cflags-only-I', 'healpix_cxx >= 3.80.0')' returned non-zero exit status 1.
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7716040Z       raise CalledProcessError(retcode, cmd)
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7716840Z   subprocess.CalledProcessError: Command '['/bin/sh', '/project/healpixsubmodule/src/cxx/configure', '--prefix=/project/build/temp.linux-x86_64-3.7', '--disable-shared', '--with-pic', '--disable-maintainer-mode']' returned non-zero exit status 1.
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7717683Z   ERROR: Failed building wheel for healpy
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:17.7717943Z ERROR: Failed to build one or more wheels
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:18.0937352Z   Building wheel for healpy (pyproject.toml): finished with status 'error'
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:18.0938664Z Checking for common errors...
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:18.1022880Z ##[error]Command ['python', '-m', 'pip', 'wheel', PurePosixPath('/project'), '--wheel-dir=/tmp/cibuildwheel/built_wheel', '--no-deps'] failed with code 1. 
Build binary packages (ubuntu-latest)   Build wheels    2022-01-15T03:33:18.1174574Z ##[error]Process completed with exit code 1.
```
Any suggestions?

**Comment by lpsinger** [comment]
I'm seeing a very different error when it's configuring healpix-cxx:

```
  checking for ffgnrwll in -lcfitsio... no
  configure: error: could not find the cfitsio library
```

Digging in config.log, the detailed error message is:

```
  configure:18173: checking for cfitsio
  configure:18180: $PKG_CONFIG --exists --print-errors "cfitsio"
  configure:18183: $? = 0
  configure:18197: $PKG_CONFIG --exists --print-errors "cfitsio"
  configure:18200: $? = 0
  configure:18238: result: yes
  configure:18249: checking for ffgnrwll in -lcfitsio
  configure:18272: gcc -pthread -o conftest -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fopenmp -I/project/build/temp.linux-x86_64-3.7/include    -fopenmp  conftest.c -lcfitsio   -L/project/build/temp.linux-x86_64-3.7/lib -lcfitsio -lcurl   -lm >&5
  /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: /project/build/temp.linux-x86_64-3.7/lib/libcfitsio.a(zcompress.o): undefined reference to symbol 'inflateInit2_'
  /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: /lib64/libz.so.1: error adding symbols: DSO missing from command line
  collect2: error: ld returned 1 exit status
  configure:18272: $? = 1
  configure: failed program was:
  | /* confdefs.h */
  | #define PACKAGE_NAME "healpix_cxx"
  | #define PACKAGE_TARNAME "healpix_cxx"
  | #define PACKAGE_VERSION "3.80.0"
  | #define PACKAGE_STRING "healpix_cxx 3.80.0"
  | #define PACKAGE_BUGREPORT ""
  | #define PACKAGE_URL ""
  | #define PACKAGE "healpix_cxx"
  | #define VERSION "3.80.0"
  | #define HAVE_STDIO_H 1
  | #define HAVE_STDLIB_H 1
  | #define HAVE_STRING_H 1
  | #define HAVE_INTTYPES_H 1
  | #define HAVE_STDINT_H 1
  | #define HAVE_STRINGS_H 1
  | #define HAVE_SYS_STAT_H 1
  | #define HAVE_SYS_TYPES_H 1
  | #define HAVE_UNISTD_H 1
  | #define STDC_HEADERS 1
  | #define HAVE_DLFCN_H 1
  | #define LT_OBJDIR ".libs/"
  | #define HAVE_CXX11 1
  | /* end confdefs.h.  */
  |
  | /* Override any GCC internal prototype to avoid an error.
  |    Use char because int might match the return type of a GCC
  |    builtin and then its argument prototype would still apply.  */
  | char ffgnrwll ();
  | int
  | main (void)
  | {
  | return ffgnrwll ();
  |   ;
  |   return 0;
  | }
  configure:18282: result: no
  configure:18288: error: could not find the cfitsio library
```

**Comment by mreineck** [comment]
Sorry, I have no idea what is going on in both cases ...

**Comment by mreineck** [comment]
Perhaps the `cfitsio` conftest machinery also needs an update for version 4?

**Comment by mreineck** [comment]
I just tried to configure the latest healpix_cxx sources on my laptop (Debian Bullseye), which has cfitsio 4.0 installed, and got no complaints from the configure script.

**Comment by lpsinger** [comment]
> Perhaps the `cfitsio` conftest machinery also needs an update for version 4?

You mean the code in healpix-cxx? Yes, that's an option.

I think that what I am seeing is indicative of a need to link against both cfitsio and zlib.

**Comment by lpsinger** [comment]
> I just tried to configure the latest healpix_cxx sources on my laptop (Debian Bullseye), which has cfitsio 4.0 installed, and got no complaints from the configure script.

This is inside the manylinux build image, though, which is based on an older yum-based distribution.

**Comment by mreineck** [comment]
> I think that what I am seeing is indicative of a need to link against both cfitsio and zlib.

That's what I thought as well at first ... but on the other hand the error message is explicitly referring to "libz.so", so the linker *knows* what it should do, and decides not to do it. I'm really confused by this.
Also, if libz is needed by libcfitsio, shouldn't pkgconfig make sure it ends up on the command line?

**Comment by lpsinger** [comment]
FWIW, this fixes it:

```diff
diff --git a/src/cxx/configure.ac b/src/cxx/configure.ac
index e63f09c..192c4fe 100644
--- a/src/cxx/configure.ac
+++ b/src/cxx/configure.ac
@@ -36,6 +36,10 @@ AC_OPENMP
 CXXFLAGS="$CXXFLAGS $OPENMP_CFLAGS"
 AC_LANG_POP([C++])
 
+PKG_CHECK_MODULES([ZLIB], [zlib], , [ZLIB_LIBS=-lz])
+CFLAGS="$CFLAGS $ZLIB_CFLAGS"
+LIBS="$LIBS $ZLIB_LIBS"
+
 dnl
 dnl Determine the compiler flags (CFITSIO_CFLAGS)
 dnl and linker flags (CFITSIO_LIBS) required to build against libcfitsio.
```

**Comment by mreineck** [comment]
Good to know, but we are really messing with autoconf here. If we say that `libz`is a direct dependency of `healpix_cxx`, how can we make sure that the libraries turn up in the right order in the linker command?
Anyway, I'm OK with this if that's the only thing holding up the release.

**Comment by lpsinger** [comment]
These two changes from https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/docs/changes.txt are causing all the trouble:

```
Version 4.0.0 - May 2021                   

  - Removed separate directory for zlib/gzip code, and updated
    configuration to check for zlib on the user's system (required).
    When use of cURL is enabled, it may also pull in zlib such
    that user applications may not need to link with it separately.

  - Changed version numbering to 3-field format.
```

We're going to need to look at the diff between cfitsio 4.0.0 and the last version. I'll take a look at the upstream tarballs. What a pain that cfitsio doesn't have a public version control repository. :shrug:

**Comment by lpsinger** [comment]
OK, cfitsio added this to their `configure.in` file:

```
# ZLIB (required):
AC_CHECK_LIB([z], [inflateEnd], [],[AC_MSG_ERROR(Unable to locate zlib compression library)])
```

There are two issues with this:

1. Shame on them for not using pkg-config here.
2. They didn't add libz to the linker flags in the cfitsio pkg-config file.

So I think that the diff I showed above is the correct workaround for healpix-cxx. @mreineck, would you please add it in svn? @zonca, once that's done, would you please update our bundled healpix-cxx code?

**Comment by mreineck** [comment]
OK, your fix is applied in r1193. Thanks for digging into this, @lpsinger!

In principle I should report this as a bug to libcfitsio, but I won't have time for the next few days. I'll try to remember it.

**Comment by mreineck** [comment]
Sorry, please use r1194 ... I forgot to bump the version number to 3.81.

**Comment by zonca** [comment]
Okay, thank you both very much. I should be able to take it from here

**Comment by zonca** [comment]
excellent, it worked fine!

**Pull request merged**
