### PR TITLE
minor

### PR DESCRIPTION
**Pull request by antolonappan**
check beam_window is array or list.

### CODE REVIEW

**Comment by zonca** [comment]
thanks!

**Comment by zonca** [comment]
I need to fix the continuous integration before I can merge this

**Comment by antolonappan** [comment]
> thanks!

No problem, For a recent usage of hp.smoothing, I accidentally gave 'beam_window = True' and the module work without error. So while debugging the wrong final result, I came across this issue.

**Comment by zonca** [comment]
See #744

**Pull request closed without merging**
