### PR TITLE
update C++ sources to 3.83

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by zonca** [comment]
I see error in cfitsio

        make: *** No rule to make target `buffers.o', needed by `libcfitsio.a'.  Stop.

**Comment by zonca** [comment]
error on Mac is:

```
        /Users/runner/work/healpy/healpy/cextern/cfitsio/config/missing: line 81: aclocal-1.16: command not found
        WARNING: 'aclocal-1.16' is missing on your system.
                 You should only need it if you modified 'acinclude.m4' or
                 'configure.ac' or m4 files included by 'configure.ac'.
                 The 'aclocal' program is part of the GNU Automake package:
                 <https://www.gnu.org/software/automake>
                 It also requires GNU Autoconf, GNU m4 and Perl in order to run:
                 <https://www.gnu.org/software/autoconf>
                 <https://www.gnu.org/software/m4/>
                 <https://www.perl.org/>
        make: *** [/Users/runner/work/healpy/healpy/cextern/cfitsio/aclocal.m4] Error 127
```

**Comment by lpsinger** [comment]
Where are you seeing that error? It looks to me like the pipeline is succeeding.

**Comment by zonca** [comment]
oh, I restarted it and it magically worked!

**Pull request merged**
