### PR TITLE
Add GitHub Actions workflow to build wheels

### PR DESCRIPTION
**Pull request by lpsinger**

### CODE REVIEW

**Comment by lpsinger** [comment]
Here is a cheese sampler for those who want an early taste of the wheels:

https://github.com/lpsinger/healpy/suites/1995803210/artifacts/39829639

**Comment by lpsinger** [comment]
For some reason, the GitHub Actions workflow isn't showing in this PR's checks. I think it will once it's merged. Meanwhile, here's a direct link to the workflow: https://github.com/lpsinger/healpy/actions/runs/549226541

Let's wait for it to complete successfully and let's take the wheels for a spin (ha ha) before we merge this.

**Comment by lpsinger** [comment]
It's done. Here are some sanity checks on my Mac (macOS 10.15.7)

- [x] macOS wheels are built with OpenMP support

    ```
    $ unzip -l healpy-1.14.0-cp39-cp39-macosx_10_9_x86_64.whl | grep omp
       331616  02-08-2021 21:03   healpy/.dylibs/libgomp.1.dylib
    ```

- [x] Linux wheels are built with OpenMP support

    ```
    $ unzip -l healpy-1.14.0-cp39-cp39-manylinux1_x86_64.whl | grep omp
        63024  02-08-2021 20:55   healpy.libs/libgomp-3300acd3.so.1.0.0
    ```

- [x] macOS wheels install and run without runtime linker errors

    ```
    $ python3.9 -m venv env
    gs66-wintermute:artifact lpsinger$ source env/bin/activate
    (env) gs66-wintermute:artifact lpsinger$ pip install healpy-1.14.0-cp39-cp39-macosx_10_9_x86_64.whl 
    Processing ./healpy-1.14.0-cp39-cp39-macosx_10_9_x86_64.whl
    Collecting matplotlib
      Using cached matplotlib-3.3.4-cp39-cp39-macosx_10_9_x86_64.whl (8.5 MB)
    Collecting scipy
      Using cached scipy-1.6.0-cp39-cp39-macosx_10_9_x86_64.whl (30.9 MB)
    Collecting astropy
      Downloading astropy-4.2-cp39-cp39-macosx_10_9_x86_64.whl (6.5 MB)
         |████████████████████████████████| 6.5 MB 2.6 MB/s 
    Collecting numpy>=1.13
      Downloading numpy-1.20.1-cp39-cp39-macosx_10_9_x86_64.whl (16.1 MB)
         |████████████████████████████████| 16.1 MB 10.1 MB/s 
    Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
      Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
    Collecting cycler>=0.10
      Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
    Collecting pillow>=6.2.0
      Using cached Pillow-8.1.0-cp39-cp39-macosx_10_10_x86_64.whl (2.2 MB)
    Collecting python-dateutil>=2.1
      Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
    Collecting kiwisolver>=1.0.1
      Using cached kiwisolver-1.3.1-cp39-cp39-macosx_10_9_x86_64.whl (61 kB)
    Collecting pyerfa
      Downloading pyerfa-1.7.2-cp39-cp39-macosx_10_9_x86_64.whl (303 kB)
         |████████████████████████████████| 303 kB 13.7 MB/s 
    Collecting six
      Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
    Installing collected packages: numpy, pyparsing, six, cycler, pillow, python-dateutil, kiwisolver, matplotlib, scipy, pyerfa, astropy, healpy
    Successfully installed astropy-4.2 cycler-0.10.0 healpy-1.14.0 kiwisolver-1.3.1 matplotlib-3.3.4 numpy-1.20.1 pillow-8.1.0 pyerfa-1.7.2 pyparsing-2.4.7 python-dateutil-2.8.1 scipy-1.6.0 six-1.15.0
    WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
    You should consider upgrading via the '/Users/lpsinger/Downloads/artifact/env/bin/python3.9 -m pip install --upgrade pip' command.
    (env) gs66-wintermute:artifact lpsinger$ python
    Python 3.9.1 (default, Dec  8 2020, 11:42:15) 
    [Clang 11.0.3 (clang-1103.0.32.62)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import healpy
    >>> ^D
    ```

- [x] Linux wheels install and run without runtime linker errors

    ```
    $ docker run --rm -it -v $(pwd):/wheels python:3.9 bash
    root@02b817b0c6a9:/# pip install /wheels/healpy-1.14.0-cp39-cp39-manylinux1_x86_64.whl 
    Processing /wheels/healpy-1.14.0-cp39-cp39-manylinux1_x86_64.whl
    Collecting scipy
      Downloading scipy-1.6.0-cp39-cp39-manylinux1_x86_64.whl (27.3 MB)
         |████████████████████████████████| 27.3 MB 462 kB/s 
    Collecting numpy>=1.13
      Downloading numpy-1.20.1-cp39-cp39-manylinux2010_x86_64.whl (15.4 MB)
         |████████████████████████████████| 15.4 MB 12.0 MB/s 
    Collecting astropy
      Downloading astropy-4.2-cp39-cp39-manylinux1_x86_64.whl (9.6 MB)
         |████████████████████████████████| 9.6 MB 11.5 MB/s 
    Collecting matplotlib
      Downloading matplotlib-3.3.4-cp39-cp39-manylinux1_x86_64.whl (11.5 MB)
         |████████████████████████████████| 11.5 MB 11.3 MB/s 
    Collecting pyerfa
      Downloading pyerfa-1.7.2-cp39-cp39-manylinux2010_x86_64.whl (698 kB)
         |████████████████████████████████| 698 kB 12.0 MB/s 
    Collecting kiwisolver>=1.0.1
      Downloading kiwisolver-1.3.1-cp39-cp39-manylinux1_x86_64.whl (1.2 MB)
         |████████████████████████████████| 1.2 MB 13.5 MB/s 
    Collecting cycler>=0.10
      Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
    Collecting pillow>=6.2.0
      Downloading Pillow-8.1.0-cp39-cp39-manylinux1_x86_64.whl (2.2 MB)
         |████████████████████████████████| 2.2 MB 14.6 MB/s 
    Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
      Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
         |████████████████████████████████| 67 kB 5.8 MB/s 
    Collecting python-dateutil>=2.1
      Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
         |████████████████████████████████| 227 kB 10.3 MB/s 
    Collecting six
      Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
    Installing collected packages: six, numpy, python-dateutil, pyparsing, pyerfa, pillow, kiwisolver, cycler, scipy, matplotlib, astropy, healpy
    Successfully installed astropy-4.2 cycler-0.10.0 healpy-1.14.0 kiwisolver-1.3.1 matplotlib-3.3.4 numpy-1.20.1 pillow-8.1.0 pyerfa-1.7.2 pyparsing-2.4.7 python-dateutil-2.8.1 scipy-1.6.0 six-1.15.0
    root@02b817b0c6a9:/# python
    Python 3.9.1 (default, Jan 12 2021, 16:45:25) 
    [GCC 8.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import healpy
    Downloading https://hpiers.obspm.fr/iers/bul/bulc/Leap_Second.dat
    |==========================================| 1.3k/1.3k (100.00%)         0s
    >>> 
    root@02b817b0c6a9:/# exit
    ```

**Comment by zonca** [comment]
ok, tested on Ubuntu and Python 3.8:

```
python -m venv env 
(base) zonca@nebula:~/p/software/healpy/wheels (master)*$ source env/bin/activate 
(env) (base) zonca@nebula:~/p/software/healpy/wheels (master)*$ which pip 
/extrahome/software/healpy/wheels/env/bin/pip 
(env) (base) zonca@nebula:~/p/software/healpy/wheels (master)*$ pip install healpy-1.14.0-cp38-cp38-manylinux1_x86_64.whl 
Processing ./healpy-1.14.0-cp38-cp38-manylinux1_x86_64.whl 
Collecting scipy (from healpy==1.14.0) 
  Using cached https://files.pythonhosted.org/packages/13/b3/acd7b4e4c78a9b56ff9739ca77f88ab7950e8e4d23cba4382480b5365e45/scipy-1.6.0-cp38-cp38-manylinux1_x86_64.whl 
Collecting numpy>=1.13 (from healpy==1.14.0) 
  Downloading https://files.pythonhosted.org/packages/c7/e6/dccac76b7e825915ffb906beeba5a953597b6cfe1fe686b5276e122cb07c/numpy-1.20.1-cp38-cp38-manylinux2010_x86_64.whl (15.4MB) 
     |████████████████████████████████| 15.4MB 12.3MB/s  
Collecting astropy (from healpy==1.14.0) 
  Downloading https://files.pythonhosted.org/packages/2e/3c/c2eb77cfc7b3e257834da500a2e3c30544d39ca802610b55f47a8e7c088a/astropy-4.2-cp38-cp38-manylinux1_x86_64.whl (9.8MB) 
     |████████████████████████████████| 9.8MB 20.8MB/s  
Collecting matplotlib (from healpy==1.14.0) 
  Downloading https://files.pythonhosted.org/packages/ab/20/60cfe5d611ac86df07b7b1f9b9582f22f7eda5edbe2124ba85bdf3133822/matplotlib-3.3.4-cp38-cp38-manylinux1_x86_64.whl (11.6MB) 
     |████████████████████████████████| 11.6MB 38.8MB/s  
Collecting pyerfa (from astropy->healpy==1.14.0) 
  Downloading https://files.pythonhosted.org/packages/12/ef/39c01df922a6910fd8ff7a8f72a40eeaefb2fdf8fb540a550895ae734f90/pyerfa-1.7.2-cp38-cp38-manylinux2010_x86_64.whl (731kB) 
     |████████████████████████████████| 737kB 29.9MB/s  
Collecting pillow>=6.2.0 (from matplotlib->healpy==1.14.0) 
  Using cached https://files.pythonhosted.org/packages/c9/57/a6c81c1d6b8973d288ec6df0993a71a61318c862afc1de71fd3aa1ba1dcd/Pillow-8.1.0-cp38-cp38-manylinux1_x86_64.whl 
Collecting python-dateutil>=2.1 (from matplotlib->healpy==1.14.0) 
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl 
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 (from matplotlib->healpy==1.14.0) 
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl 
Collecting kiwisolver>=1.0.1 (from matplotlib->healpy==1.14.0) 
  Using cached https://files.pythonhosted.org/packages/99/04/41e831621ddec54f99e9e3693b8d4f2f583d7f3ee8df33bf9a7d6bf764de/kiwisolver-1.3.1-cp38-cp38-manylinux1_x86_64.whl 
Collecting cycler>=0.10 (from matplotlib->healpy==1.14.0) 
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl 
Collecting six>=1.5 (from python-dateutil>=2.1->matplotlib->healpy==1.14.0) 
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl 
Installing collected packages: numpy, scipy, pyerfa, astropy, pillow, six, python-dateutil, pyparsing, kiwisolver, cycler, matplotlib, healpy 
Successfully installed astropy-4.2 cycler-0.10.0 healpy-1.14.0 kiwisolver-1.3.1 matplotlib-3.3.4 numpy-1.20.1 pillow-8.1.0 pyerfa-1.7.2 pyparsing-2.4.7 python-dateutil-2.8.1 scipy-1.6.0 six-1.15.0 
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available. 
You should consider upgrading via the 'pip install --upgrade pip' command. 
(env) (base) zonca@nebula:~/p/software/healpy/wheels (master)*$ python  
Python 3.8.3 (default, May 19 2020, 18:47:26)  
[GCC 7.3.0] :: Anaconda, Inc. on linux 
Type "help", "copyright", "credits" or "license" for more information. 
>>> import healpy 
Downloading https://hpiers.obspm.fr/iers/bul/bulc/Leap_Second.dat 
|================================================================================| 1.3k/1.3k (100.00%)         0s 
>>>  
```

**Comment by lpsinger** [comment]
Note, I've added a PyPI API token to the repository secrets.

**Pull request merged**
