### PR TITLE
Fix const correctness in Numpy ufunc API

### PR DESCRIPTION
**Pull request by lpsinger**
Fixes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964655.

### CODE REVIEW

**Comment by mreineck** [comment]
I like it!

**Comment by lpsinger** [comment]
The tests are failing because the const qualifier was aded in numpy/numpy#15355. The patch here needs to be a bit more subtle. Either we can use error and warning pragmas to temporarily adjust the compiler error settings in the affected code, or we can add a macro/typedef that depends on the Numpy version.

**Comment by mreineck** [comment]
Do I understand this correctly: the `numpy` developers changed the interface in a way that breaks existing code (OK so far), but now all the broken code needs a really ugly hack to be compatible with old and new `numpy` versions? Yuck ...

**Comment by lpsinger** [comment]
Correct.

**Comment by lpsinger** [comment]
Adding explicit casts to `PyUFuncGenericFunction` fixed it. Builds are passing now, please review.

**Pull request merged**
