### PR TITLE
Use alice3 from libhealpix_cxx

### PR DESCRIPTION
**Pull request by lpsinger**

### CODE REVIEW

**Comment by lpsinger** [comment]
@mreineck, would you please incorporate this patch into the Subversion repository?

```diff
diff --git a/src/cxx/configure.ac b/src/cxx/configure.ac
index 04f854c..d38e1e0 100644
--- a/src/cxx/configure.ac
+++ b/src/cxx/configure.ac
@@ -1,4 +1,4 @@
-AC_INIT([healpix_cxx],[3.82.0])
+AC_INIT([healpix_cxx],[3.83.0])
 AM_INIT_AUTOMAKE([foreign subdir-objects -Wall -Werror])
 AM_MAINTAINER_MODE([enable])
 
```

**Comment by mreineck** [comment]
I'm confused, as far as I can tell this is in the subversion repo since revision 1238 (2024-04-17).

**Comment by mreineck** [comment]
Ah, perhaps you are are not using the trunk of the svn repo?

**Comment by lpsinger** [comment]
@zonca, would you please check if there are more commits on trunk that we need to sync?

**Pull request merged**
