### PR TITLE
return a result when boundaries() is called with the healpixels given as python list

### PR DESCRIPTION
**Pull request by segasai**
Hi, 
currently when boundaries() method is called like this 

healpy.boundaries(2,[2,3]) 
it returns None 

This pull requests fixes this by trying to cast the input to a numpy array.

Cheers,
        Sergey

### CODE REVIEW

**Comment by lpsinger** [comment]
Nice bugfix. I would suggest revamping the type checking to use `np.isscalar` and `np.can_cast`, as those functions have sorted out all the corner cases of different numeric and collection types.

**Comment by segasai** [comment]
Okay, I'll take a look at np.can_cast & np.isscalar

**Comment by zonca** [comment]
@segasai, do you plan to work more on this? Thanks!

**Comment by zonca** [comment]
moved to #279

**Pull request closed without merging**
