### PR TITLE
Python 3 compatibility: alias long to int

### PR DESCRIPTION
**Pull request by evertrol**
This prevents an exception at the line 

    bins = long(min(data2.size/20, 5000))

### CODE REVIEW

**Comment by lpsinger** [comment]
I'm not sure why the cast to `long` was necessary in the first place. How about just changing this line to use true division (`//`) and no cast?

        bins = min(data2.size//20, 5000)

**Comment by evertrol** [comment]
I've changed the PR to use integer divison instead.

**Comment by zonca** [comment]
Thanks!

**Comment by lpsinger** [comment]
:+1:

**Pull request merged**
