### PR TITLE
Allow read_map to also take an HDUList or HDU instance

### PR DESCRIPTION
**Pull request by astrofrog**
Not tested yet since I'm having issues compiling healpy on my machine, but hopefully Travis can do the testing :smile:

### CODE REVIEW

**Comment by lpsinger** [comment]
Nice! Could you do the same for `read_cl`, `read_alm`, `write_map`, `write_cl`, and `write_alm`?

**Comment by astrofrog** [comment]
@lpsinger - I implemented this for the read functions using a helper function. I don't think it makes sense for the write functions though? I also did some minor PEP8 cleanup.

**Comment by lpsinger** [comment]
> I don't think it makes sense for the write functions though?

Why not?

**Comment by astrofrog** [comment]
@lpsinger - so I guess you mean that if I passed an HDU, it would write the data to that HDU? Or that the ``write`` functions could either write to a file or return an HDU?

**Comment by lpsinger** [comment]
> @lpsinger - so I guess you mean that if I passed an HDU, it would write the data to that HDU? Or that the write functions could either write to a file or return an HDU?

Oh, I see the issue... maybe we just want to factor the writing into a function that creates and HDU and a function that calls that and then writes it to a FITS file.

**Comment by zonca** [comment]
Thanks @astrofrog,
@lpsinger fine with me.

**Comment by astrofrog** [comment]
@lpsinger - unit tests added

**Comment by lpsinger** [comment]
Nice! :+1: to merge.

**Comment by zonca** [comment]
thanks

**Comment by lpsinger** [comment]
Hey @zonca. Do you have any releases coming up? I'd like to use this feature in one of my projects.

**Comment by zonca** [comment]
yes, I need also one of the bugfixes in mollview. I'd release a new version
next week.

**Pull request merged**
