### PR TITLE
warnings to logging and deprecate verbose

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by zonca** [comment]
@kadrlica could you please review this PR?

**Comment by kadrlica** [comment]
Sorry, it's going to be a little while before I can review this in detail.

**Comment by zonca** [comment]
rebased on latest updates to main

**Comment by zonca** [comment]
@kadrlica if you are interested, please review by Thursday the 27th

**Comment by kadrlica** [comment]
I've given the changes a quick look, and they looked ok to me. This was too quick to be called a proper "review", but hopefully it is better than nothing.

**Comment by zonca** [comment]
rebased on main

**Pull request merged**
