### PR TITLE
TEST: using travis new container infrastructure

### PR DESCRIPTION
**Pull request by zonca**
cannot use sudo, using addons apt instead

### CODE REVIEW

**Comment by lpsinger** [comment]
I think it is still important to have tests that use `pip`.

**Comment by zonca** [comment]
@lpsinger sure, trying to keep all the same tests

**Comment by zonca** [comment]
@lpsinger I think this is pretty good.

however I cannot implement the removal of packages:

    sudo apt-get -y remove autoconf automake pkg-config && \

do you think this is important?

**Comment by lpsinger** [comment]
> do you think this is important?

Yes, it's important. Those packages need to be removed because we are testing that the package builds without a full autotools developer installation.

**Comment by zonca** [comment]
ok, asked to the support of travis-ci

**Comment by zonca** [comment]
travis-ci confirmed it is not possible to remove packages in the new infrastructure, so let's keep using the legacy infrastructure for now.

**Pull request closed without merging**
