### PR TITLE
updated healpix CXX to 786 (trunk)

### PR DESCRIPTION
**Pull request by zonca**
/cc @mreineck

### CODE REVIEW

**Comment by zonca** [comment]
@mreineck the build fails on Travis with:

    healpy/src/_healpy_sph_transform_lib.cc:923:27: error: ‘struct std::complex<double>’ has no member named ‘im’

however it works on my newer ubuntu.
do you have a suggestion on what might be the problem?

**Comment by mreineck** [comment]
The complex data type used by Healpix_cxx is now the standard one from C++, and that one does not have the direct access to .re and .im. I have no idea why it fails for you on one target, but works on the other. Tihs indicates a bug in the build dependencies ... maybe Cython has not be re-run when it should.
In any case, I'll check the (not automatically generated) C++ sources in healpy and make changes, if necessary.

**Comment by zonca** [comment]
I see tests failing on all targets

**Comment by mreineck** [comment]
The C++ interface code in healpy/src should not even compile at the moment. If it still does, there is, as I said, a bug in setup.py somewhere.

**Comment by mreineck** [comment]
How should I provide the necessary changes? Pull request on top of your changes?

**Comment by zonca** [comment]
Yes, pull request on my branch zonca/update...

**Comment by mreineck** [comment]
I hope to have something usable by lunchtime tomorrow.

**Comment by mreineck** [comment]
Aargh, I think I'm too stupid for this ...
I have forked healpy and cloned my fork locally. How can I now access a branch in your fork?

**Comment by zonca** [comment]
origin is mreinek/healpy

    git remote add zonca myfork
    git checkout -b update... zonca/update...
    git push -u origin update...

then go to github and create a pull request from mreinek/update.. to
zonca/update..

**Comment by zonca** [comment]
myfork is the address of my fork zonca/healpy

**Comment by mreineck** [comment]
OK, pull request created, and it seems to pass the tests.

**Comment by zonca** [comment]
thanks @mreineck

**Comment by lpsinger** [comment]
This will break API and BI compatibility with older versions of healpix_cxx. Just checking, are we doing a simultaneous healpix_cxx release?

**Comment by zonca** [comment]
@lpsinger yes, they are preparing a release, @mreineck when do you plan to make the release?

**Comment by lpsinger** [comment]
We'll need autotools source packages for healpix_cxx to regenerate packages for Scientific Linux and Debian.

**Comment by mreineck** [comment]
@zonca I don't get to decide about release dates, but it feels like "in the next few weeks".

@lpsinger Do you want a prerelease package now for testing or do you prefer to wait until release?

**Pull request merged**
