### PR TITLE
remove pytest-runner from pyproject.toml

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by lpsinger** [comment]
You absolutely still need pytest-runner if you want `python setup.py test` to work.

**Comment by zonca** [comment]
what if we deprecate `python setup.py test`?

like it's done in the astropy package template (changing the error message):

https://github.com/astropy/package-template/blob/bf8ce319e8ec99c38ab80c8af8c0437c16de0474/%7B%7B%20cookiecutter.package_name%20%7D%7D/setup.py#L18-L41

**Comment by lpsinger** [comment]
Fine with me, but that would involve more updates to setup.py, updates to the CI script, and updates to the instructions too.

**Comment by zonca** [comment]
The CI script already uses pytest

**Pull request merged**
