### PR TITLE
Add beam_window variable to smoothing routines in sphtfunc.py

### PR DESCRIPTION
**Pull request by j-erler**
Small modification to allow to pass custom beam window functions like e.g. matched filters to the smoothing routines in sphtfunc.py. Adds new optional variable beam_window to sphtfunc.smoothing and sphtfunc.smoothalm.

Second commit adds translations of the healpix functions beam2bl and bl2beam. These functions allow transformations of beams to window functions and vise versa.

### CODE REVIEW

**Comment by zonca** [comment]
thanks! can you also please add unit tests?

**Comment by zonca** [comment]
Yes, no problem about scipy

**Comment by j-erler** [comment]
Ok, I will add unit tests in a separate pull request.

**Comment by zonca** [comment]
Better to add unit tests here, so I review all together and merge

**Comment by j-erler** [comment]
I added the unit tests and fixed a minor bug in beam2bl.

**Pull request merged**
