### PR TITLE
DO NOT MERGE: For testing only

### PR DESCRIPTION
**Pull request by pllim**
**DO NOT MERGE**

Just want to see if problem reported in #442 can be fixed with astropy/astropy#7493 . Sorry for the noise.

### CODE REVIEW

**Comment by zonca** [comment]
It looks good!

**Comment by pllim** [comment]
Well, this is weird... Why did the error never show up for `USE_ANACONDA=true` and only for *some* of the Python 2.7 tests back in https://travis-ci.org/healpy/healpy/builds/382791316 ? Maybe `healpy` should report version numbers of dependencies (numpy, astropy, etc) being tested. With the currently log, I have no idea what Astropy version is being pulled by which test job.

**Comment by pllim** [comment]
Anyway, tests passed, so I am closing this PR to avoid confusion.

**Comment by zonca** [comment]
Yeah I noticed that it is because anaconda has older version of Astro pi

Il mar 29 mag 2018, 19:14 P. L. Lim <notifications@github.com> ha scritto:

**Comment by zonca** [comment]
it is not, I don't know why `conda` picked up a older version, I found out about it in the logs

**Comment by pllim** [comment]
:scream:

**Comment by zonca** [comment]
no way I'm digging into conda dependency resolution! ;)

**Pull request closed without merging**
