### PR TITLE
Fixed build on readthedocs

### PR DESCRIPTION
**Pull request by zonca**
finally got around to fix this.

@lpsinger I had to set `setuptools==12.0.5` in `requirements.txt`.
Do you think this could have implications for the install process?

### CODE REVIEW

**Comment by zonca** [comment]
See the branch documentation on http://healpy.readthedocs.org/en/testreadthedocs/tutorial.html

**Comment by lpsinger** [comment]
> @lpsinger I had to set setuptools==12.0.5 in requirements.txt.
> Do you think this could have implications for the install process?

It's great if this is an easy solution to fixing the readthedocs build, but I'd rather not force everyone to upgrade setuptools. Healpy will build with anything newer than setuptools 3.2.

What happens if instead you update the setuptools bootstrap script to [the latest version](https://bootstrap.pypa.io/ez_setup.py)?

**Comment by zonca** [comment]
Let's try

**Comment by zonca** [comment]
it worked!

**Comment by zonca** [comment]
Cleaned up to a single commit.

**Comment by lpsinger** [comment]
:+1:

**Comment by lpsinger** [comment]
OK to delete the `testreadthedocs` branch?

**Comment by zonca** [comment]
it is failing again: https://readthedocs.org/builds/healpy/2509652/

**Pull request merged**
