### PR TITLE
Update HEALPix from SVN r1192 for HEALPix 3.81

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by lpsinger** [comment]
Does the minimum version of healpix-cxx in setup.py need to be updated? What is the minimum version of healpix-cxx that is compatible with healpy?

**Comment by zonca** [comment]
> Does the minimum version of healpix-cxx in setup.py need to be updated? What is the minimum version of healpix-cxx that is compatible with healpy?

yes, I fixed that

**Comment by lpsinger** [comment]
Has this version been released? I'd feel better about updating to a released version.

**Comment by zonca** [comment]
Eric is waiting on me to package the next version of healpy so that he can
release healpix and bundle healpy.

**Comment by zonca** [comment]
The minimum version that I put in setup is 3.80 and that has already been
released.
Eric  will release 3.81

**Comment by zonca** [comment]
see f0158e8

**Comment by lpsinger** [comment]
LGTM.

**Pull request merged**
