### PR TITLE
Replace obsolete ez_setup.py with PEP 518 pyproject.toml

### PR DESCRIPTION
**Pull request by lpsinger**
This simplifies and modernizes bootstrapping setuptools and including build dependencies.

### CODE REVIEW

**Comment by mreineck** [comment]
This is almost certainly off-topic, but I found it while reading the new `pyproject.toml`...

Why is there still a dependency on `six`? `healpy` is now Python 3 only, correct?

**Comment by lpsinger** [comment]
> This is almost certainly off-topic, but I found it while reading the new `pyproject.toml`...
> 
> Why is there still a dependency on `six`? `healpy` is now Python 3 only, correct?

No, not yet. That's in a separate PR. See #658.

**Comment by lpsinger** [comment]
Note, this will make it easier to build wheels (#656).

**Review by zonca — APPROVED** [review]
it looks good to me, go ahead and merge when ready

**Pull request merged**
