### PR TITLE
Several changes to fix building of wheels

### PR DESCRIPTION
**Pull request by lpsinger**

### CODE REVIEW

**Comment by zonca** [comment]
Thank you very much for fixing this

**Comment by zonca** [comment]
@lpsinger I just noticed that the linux one didn't pass, it actually timed out after 6 hours:

https://github.com/healpy/healpy/runs/4813376952?check_suite_focus=true

**Comment by lpsinger** [comment]
Yeah, it's building lots of wheels serially. I'll research what is the best way to parallelize cibuildwheel in GitHub Actions.

**Comment by zonca** [comment]
it seems the problem is the testing on one of the wheels, building and testing the wheels takes 5 minutes each

**Pull request merged**
